### PR TITLE
Tests for LinearLocalModel and Weighting Function

### LINKED ISSUE #22: Add tests for LinearLocalModel
There aren't any tests for `LinearLocalModel` in teh file `localmodeling_tests.jl`. THis would have caught the wrong definition of `LinearLocalModel` done in #20

### PR DESCRIPTION
**Pull request by JonasIsensee**
Please review!

closes #22

### CODE REVIEW

File: test/localmodeling_tests.jl [hunk 1]
```diff
@@ -29,6 +29,42 @@ s_test  = data[N_train:end,1]
...
+        @test norm(s_test[1:p+1] - s_pred)/p < 5e-2
+
+        #Repeat with reconstruction given
+        R = Reconstruction(s_train, D, τ)
+        s_pred = localmodel_tsp(R, p; method=method, ntype=ntype, stepsize=stepsize)[:,D]
+        @test length(s_pred) == p+1
+        @test norm(s_test[1:p+1] - s_pred)/p < 5e-2
+    end
+
+    @testset "D=$D and τ=$τ" for D ∈ [3,4], τ ∈ [14,15]
```
Comment (Datseris) [inline test/localmodeling_tests.jl]: This test title is not very well descriptive. 
How about making one more outer loop of `@testset` that says which method you are using? If only one of the two linear models fail, you won't be able to immediately tell which one of the 2 from the report.

File: test/st_pred_tests.jl [hunk 2]
```diff
@@ -19,6 +19,16 @@ include("system_defs.jl")
     vtest  = V[N_train:N_train+p]
 
     @testset "D=$D, B=$B" for D=2:3, B=1:2
+        method = AverageLocalModel()
```
Comment (Datseris) [inline test/st_pred_tests.jl]: Same thing. The test tile is `D =...` but it should be `ALM D = ...`

**Comment by Datseris** [comment]
will merge *if* tests pass
